# Numpy Intro

### Load basic libraries

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Numpy basic operations

What provides Numpy:

- ndarray --> fast and space-efficient multidimensional array with vectorized arithmetic operations and sophisticated broadcasting capabilities

- Standard mathematical functions for fast operations on entire arrays of data without using loops

- Read/Write tools for transfering data to disk or working with memory-mapped files

- Linear algebra, random number generation and Fourier transform capabilities

- Tools for integrating code written in C, C++, and Fortran

While NumPy by itself does not provide very much high-level data analytical functionality, having an understanding of NumPy arrays and array-oriented computing will help you use tools like pandas much more effectively.

In [2]:
x = np.array([1, 2, 3])                                    # Create a rank 1 array
print(f"x type: {type(x)}")                                # Prints "<class 'numpy.ndarray'>"
print(f"x shape: {x.shape}")                               # Prints "(3,)"
print(f"Values referenced by index: {x[0], x[1], x[2]}")   # Prints "1 2 3"
x[0] = 5                                                   # Change an element of the array
print(f"Final x after modification: {x}\n")                # Prints "[5, 2, 3]"

y = np.array([[1,2,3],[4,5,6]])                            # Create a rank 2 array
print(f"y shape: {y.shape}")                               # Prints "(2, 3)"
print(y[0, 0], y[0, 1], y[1, 0])                           # Prints "1 2 4"

x type: <class 'numpy.ndarray'>
x shape: (3,)
Values referenced by index: (1, 2, 3)
Final x after modification: [5 2 3]

y shape: (2, 3)
1 2 4


In [3]:
x = np.zeros((2, 2))                  # Create an array of all zeros
print(f"Array of zeros\n{x}")         # Prints "[[ 0.  0.]
                                      #          [ 0.  0.]]"

y = np.ones((1, 2))                   # Create an array of all ones
print(f"Array of ones\n{y}")          # Prints "[[ 1.  1.]]"

cte = np.full((2, 2), 7)              # Create a constant array
print(f"Array with constant\n{cte}")  # Prints "[[ 7.  7.]
                                      #          [ 7.  7.]]"

d = np.eye(2)                         # Create a 2x2 identity matrix
print(f"Identity matrix\n{d}")        # Prints "[[ 1.  0.]
                                      #          [ 0.  1.]]"

r = np.random.random((2, 2))          # Create an array filled with random values
print(f"Matrix with random values\n{r}")

e = np.empty((3, 3))                  # Allocate matrix without initializing the values
print(f"Matrix created using empty\n{e}")

Array of zeros
[[0. 0.]
 [0. 0.]]
Array of ones
[[1. 1.]]
Array with constant
[[7 7]
 [7 7]]
Identity matrix
[[1. 0.]
 [0. 1.]]
Matrix with random values
[[0.29453875 0.20284247]
 [0.24217448 0.67581005]]
Matrix created using empty
[[ 2.19601440e-314  4.58020255e-114  2.19631723e-314]
 [ 2.19621934e-314 -2.11523641e-015  2.16034530e-314]
 [ 2.15148370e-314  6.60683570e+236  2.15314911e-314]]


<font color=red>NOTE: It’s not safe to assume that np.empty will return an array of all zeros. In many cases, as previously shown, it will return uninitialized garbage values.</font>

### Array Indexing and Slicing

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array.

Note that np.array tries to infer a good data type for the array that it creates. The data type is stored in a special dtype object.

In [4]:
arr = np.arange(10)                           # Create a sequence from 0 to 9
print(f"Initial array: {arr}")
print(f"Value at index 5: {arr[5]}")
print(f"Slice from 5 to 8: {arr[5:8]}")
print(f"Last two elements: {arr[-2:]}")

arr_mod = arr.copy()                          # Create a copy of the array
arr_mod[5:8] = 21                             # Overwrite the values at 5, 6 and 7
print(f"Modified array: {arr_mod}")
print(f"Initial array: {arr}")                # Original is still the same

Initial array: [0 1 2 3 4 5 6 7 8 9]
Value at index 5: 5
Slice from 5 to 8: [5 6 7]
Last two elements: [8 9]
Modified array: [ 0  1  2  3  4 21 21 21  8  9]
Initial array: [0 1 2 3 4 5 6 7 8 9]


In [5]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [6]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; y is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
y = x[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(x[0, 1])   # Prints "2"
y[0, 0] = 77     # y[0, 0] is the same piece of data as x[0, 1]
print(x[0, 1])   # Prints "77"

2
77


In [7]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:
row_r1 = x[1, :]    # Rank 1 view of the second row of x
row_r2 = x[1:2, :]  # Rank 2 view of the second row of x
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = x[:, 1]
col_r2 = x[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [8]:
x = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing. The returned array will have shape (3,) and Prints "[1 4 5]"
print(x[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([x[0, 0], x[1, 1], x[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same element from the source array:
print(x[[0, 0], [1, 1]])              # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([x[0, 1], x[0, 1]]))   # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


Using array indexing we can select or mutate one element from each row of a matrix:

In [9]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
# Create an array of indices
idx = np.array([0, 2, 0, 1])

# Select one element from each row using the indices in idx for selecting the value within the row
print(x[np.arange(4), idx])        # Prints "[ 1  6  7 11]"

# Mutate one element from each row using the indices in idx.
x[np.arange(4), idx] += 10

# Print final result of 'x'
print(x)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [10]:
x = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (x > 2)      # Find the elements of a that are bigger than 2;
                        # this returns a numpy array of Booleans of the same shape as x
                        # where each slot of bool_idx tells whether that element of a is > 2.

print(bool_idx)         # Prints "[[False False]
                        #          [ True  True]
                        #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array consisting
# of the elements of a corresponding to the True values of bool_idx
print(x[bool_idx])     # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(x[x > 2])        # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes

Every numpy array is a grid of *elements of the same type*. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [11]:
x = np.array([1, 2])                   # Let numpy choose the datatype
print(x.dtype)                         # Prints "int64"

x = np.array([1.0, 2.0])               # Let numpy choose the datatype
print(x.dtype)                         # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


Valid datatypes include:
- int8, uint8
- int16, uint16
- int32, uint32
- int64, uint64
- float16
- float32
- float64
- float128
- complex64, complex128, complex256
- bool
- object
- string_
- unicode_

<font color=red>It’s worth keeping in mind that floating point numbers, such as those in float64 and float32 arrays, are only capable of approximating fractional quantities. In complex computations, you may accrue some floating point error, making comparisons only valid up to a certain number of decimal places.</font>

## Math

Basic mathematical functions operate elementwise on arrays and are available both as operator overloads and as functions in the numpy module:

In [12]:
z = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]], dtype=np.float64)

print(z * 10)                          # Multiply all elements of the array

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


**\*** is elementwise multiplication, not matrix multiplication. We instead use the **dot** function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [14]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [15]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))          # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

Broadcasting allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example suppose that we want to add a constant vector to each row of a matrix. 

In [16]:
# We will add the vector v to each row of the matrix x, storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)        # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


However when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [17]:
# We will add the vector v to each row of the matrix x, storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider the following version:

In [18]:
# We will add the vector v to each row of the matrix x, storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v       # Add v to each row of x using broadcasting
print(y)        # Prints "[[ 2  2  4]
                #          [ 5  5  7]
                #          [ 8  8 10]
                #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:

- If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
- The arrays can be broadcast together if they are compatible in all dimensions.
- After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
- In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Functions that support broadcasting are known as **[Universal Functions](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs)**

Some applications of broadcasting include:

In [19]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

## Scipy

Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays.

SciPy builds on this and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.

For example SciPy provides some basic functions to work with images. Read images from disk into numpy arrays, write numpy arrays to disk as images and resize images.

In [20]:
# if you don't have the package...
# !pip install scipy
import scipy

scipy?

#### Input / Output package

In [21]:
from scipy import io as sio

array = np.array(6810936512)
sio.savemat('jeff_bank_account.mat', {'data': array}) 
data = sio.loadmat('jeff_bank_account.mat', struct_as_record=True)
data['data']

array([[6810936512]])

#### Special function package

scipy.special contains numerous functions of mathematical physics:

Cubic Root, Exponential, Log sum Exponential, Lambert, Permutation and Combinations, Gamma, Bessel, hypergeometric, Kelvin, beta, parabolic cylinder, Relative Error Exponential, etc..

type: help(scipy.special)

<font color=red>Note: <br>By default, "import scipy" does not import any subpackage so unless we explicitelly import scipy.special we may encounter "module 'scipy' has no attribute [attribute-name]" errors...</font>


AttributeError: module 'scipy' has no attribute 'special'

### Distance between points

The function scipy.spatial.distance.pdist computes the distance between all pairs of points in a given set:

In [20]:
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]
